github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-example-chart
      useSinglePullRequest: true
    - name: activiti-cloud-example-chart-security-policies
      useSinglePullRequest: true
